name: readme generator

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: generate chinese readme
        uses: eryajf/yaml-readme@master
        env:
          GH_TOKEN: ${{ secrets.GH_SECRETS }}
        with:
          pattern: 'items/*/*.yaml'
          template: 'template/README.tpl'
          output: 'README.md'
          username: "yeshan333"
          org: yeshan333
          repo: awesome-tech-weekly-zh
          sortby: kind
          groupby: kind
          header: false
      - name: generate english readme
        uses: eryajf/yaml-readme@master
        env:
          GH_TOKEN: ${{ secrets.GH_SECRETS }}
        with:
          pattern: 'items/*/*.yaml'
          username: "yeshan333"
          org: yeshan333
          repo: awesome-tech-weekly-zh
          sortby: kind
          groupby: kind
          header: false
          template: 'template/README-en.tpl'
          output: 'resources/README-en.md'